## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

### 1.1. Numpy Array creation

In [1]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [ ]:
# 파이썬 리스트 선언


In [ ]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = 

In [ ]:
# 파이썬 list를 numpy array로 변환합니다.

# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.


In [ ]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.


In [ ]:
# 0부터 9까지 숫자를 자동으로 생성한 array


In [ ]:
# 10부터 99까지 숫자를 자동으로 생성한 array


### 1.2. Reshaping array

In [ ]:
# 3 x 3 행렬을 만들어봅시다.
x = 

In [ ]:
# reshape을 이용하여 만들어봅시다.


In [ ]:
# row vector를 column vector로


In [ ]:
# 펼치기


### 1.3. Concatenation of arrays

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1 + arr2 = ?
arr1 + arr2
# arr1와 arr2를 합칩니다

array([5, 7, 9])

In [4]:
# stacking vertically
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# stacking horizontally
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [6]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [7]:
# 리스트로 더하기 연산해보기
L1 = [1, 2, 3]
L2 = [4, 5, 6]
L1 + L2

[1, 2, 3, 4, 5, 6]

In [8]:
#  vector addition
v1 + v2

array([5, 7, 9])

In [10]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [11]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [12]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [13]:
# dot product
v1 @ v2

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [14]:
arr1 = np.array([1, 0, 0])

In [17]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [18]:
# 2개의 array를 더해보면?
arr1 + arr2 # 2->2->3(v)

array([[2, 2, 3],
       [5, 5, 6]])

In [19]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[1, 0, 0],
       [4, 0, 0]])

- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [20]:
# f = lambda x : 1/x
1 / arr1

/var/folders/4h/b2cqm88s3cl_l0lpwl10b69r0000gn/T/ipykernel_24600/704277822.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr1


array([ 1., inf, inf])

In [21]:
# f = lambda x : x + 2
2 + arr1

array([3, 2, 2])

### 1.6. Indexing


In [ ]:
arr1 = np.arange(10)

In [ ]:
# 첫번째 원소


In [ ]:
# 마지막 원소


In [ ]:
# 앞에서부터 원소 3개 slicing


In [2]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# arr2의 2row, 3column 원소 = 7


In [ ]:
# arr2의 세번째 column [3, 7, 11]


In [ ]:
# arr2의 두번째 row


## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [ ]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
mat1 = 

In [ ]:
# mat1에 절대값 씌우기


In [ ]:
# mat1 제곱하기


In [ ]:
# mat1의 제곱근 구하기


In [ ]:
# linear algebra functions
vec = 

# 1. norm


# 2. eigenvalue


### 2.2. Aggregation functions 

In [31]:
np.random.seed(42) # seed set  ## reproducibility
mat2 = np.random.rand(3, 2)
mat2

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [ ]:
# Summation


In [ ]:
# mean
np.mean(mat3, axis=0)

In [35]:
# std
mat2

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

In [32]:
# min, max
np.min(mat2, axis=0)

array([0.15601864, 0.15599452])

In [33]:
np.max(mat2, axis=1)

array([0.95071431, 0.73199394, 0.15601864])

In [34]:
# 최소값이 있는 Index
np.argmin(mat2, axis=1)

array([0, 1, 1])

In [36]:
# 최대값이 있는 Index
np.argmax(mat2, axis=0)

array([1, 0])

In [38]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)
np.sort(mat2, axis=0) # default > axis=1

array([[0.15601864, 0.15599452],
       [0.37454012, 0.59865848],
       [0.73199394, 0.95071431]])

In [39]:
# index를 정렬
np.argsort(mat2, axis=0)

array([[2, 2],
       [0, 1],
       [1, 0]])

## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [50]:
np.random.seed(0)

def reverse_num(values): # 함수로 정의했기 때문에 오버헤드가 발생
    output = np.empty(len(values)) 
    
    for i in range(len(values)): # dynamic type binding
        output[i] = 1.0 / values[i]
    
    return output

In [57]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 101, 100000000)
big_array

array([30, 61, 97, ..., 48,  8, 23])

In [55]:
%timeit reverse_num(big_array)

1min 7s ± 273 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
%timeit 1.0 / big_array

96.4 ms ± 179 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 결론: 데이터가 많으면 많을 수록 브로드캐스트, 유니버셜 펑션을 사용하는 것이 좋다!